---
# title: "Confirmatory Factor Analysis"
format: html
execute:
  warning: false
---

# Imports

```{r, include=FALSE, echo=FALSE}
library(tidyverse)
library(lavaan) # Structural Equation Modeling
library(corrr) # Used for getting all pairs of columns with colpair_map
library(DescTools) # Used for confidence intervals with Kendall's Tau
library(semPlot) # Path diagrams
library(semptools) # Customize SEM plots
library(semTools) # Extract metrics from SEM models (AVE)
library(ggplot2)
library(ggalluvial) # Sankey diagrams
library(ggrepel) # Dodge overlapping text elements in ggplot
library(corrplot) # For drawing correlation plots
library(stargazer) # For outputting HTML tables
library(philentropy) # Distance metrics (KL Divergence)
library(irr)
```

## Calculate probability distribution of scores in the training data

This will be used to convert the floating point deberta outputs into ordinal-scaled scores.

```{r}
train <- read_csv("../data/ellipse_partitioned.csv", show_col_types = FALSE) %>% 
  filter(str_detect(partition, "train")) %>% 
  select(c("overall_1", "overall_2")) %>% 
  sapply(table) %>%
  t() %>%
  return()

train <- train[, colnames(train) != "0"]
probs <- train/rowSums(train)
deberta_1_probs <- as.vector(probs[1,])
deberta_2_probs <- as.vector(probs[2,])
```

## Data

```{r}
data_path <- "../results/deberta-cfa.csv"

df_in <- read_csv(data_path, show_col_types = FALSE) %>% 
  rename_all(make.names) %>% 
  rename_all(tolower) %>% 
  filter(overall_1 > 0)  %>%
  return()

df_rounded <- df_in %>%
  mutate(across(starts_with("deberta"), round)) %>%
  mutate(across(matches(".*_[12]$"), \(x) factor(
    x,
    ordered=TRUE,
    levels=1:5,
    labels=c("1", "2", "3", "4", "5")
    )))

df <- df_in %>% 
  mutate(deberta_overall_1 = cut(deberta_overall_1, 
                       breaks = quantile(deberta_overall_1, probs=c(0, cumsum(deberta_1_probs))),
                       labels = 1:5,
                       include.lowest = TRUE)) %>% 
  mutate(deberta_overall_2 = cut(deberta_overall_2, 
                       breaks = quantile(deberta_overall_2, probs=c(0, cumsum(deberta_2_probs))),
                       labels = 1:5,
                       include.lowest = TRUE)) %>% 
  mutate(across(matches(".*_[12]$"), \(x) factor(
    x,
    ordered=TRUE,
    levels=1:5,
    labels=c("1", "2", "3", "4", "5")
    )))
  
```

## Disagreements

```{r}
table(df$overall_1,df$overall_2)

ggplot(data = df,
       aes(
         axis1 = overall_1,
         axis2 = overall_2
         )) +
  scale_x_discrete(limits=c("Rater 1", "Rater 2")) +
  geom_alluvium(aes(fill=overall_1)) +
  geom_stratum(alpha=0.15, color="black") +
  geom_text_repel(
    stat="stratum",
    aes(label = after_stat(stratum)),
    direction="y",
    nudge_x = 0.25
    ) +
  theme_minimal() +
  labs(
    title = "Overall Proficiency Scores by Rater",
    y = "Count",
    x = "Rater",
    fill="Score"
  )
ggsave("sankey.png", width=7, height=4, dpi=300)
```
```{r}
ggplot(data = df,
       aes(
         axis1 = overall_1,
         axis2 = overall_2
       )) +
  scale_x_discrete(limits=c("Rater 1", "Rater 2")) +
  # Using grayscale with different opacities
  geom_alluvium(aes(fill = overall_1)) +
  geom_stratum() +
  geom_text_repel(
    stat = "stratum",
    aes(label = after_stat(stratum)),
    direction = "y",
    nudge_x = 0.25
  ) +
  # Grayscale palette
  scale_fill_grey(start = .9, end = .0) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    legend.position = "bottom",
    axis.text = element_text(color = "black")
  ) +
  labs(
    title = "Overall Proficiency Scores by Rater",
    y = "Count",
    x = "Rater",
    fill = "Score"
  )
```



## Score Distributions by Rating Method

```{r}

plot_data <- df %>%
  select(matches(".*overall_[12]$")) %>%
  setNames(c("Rater 1", "Rater 2", "Deberta 1", "Deberta 2"))

plot_data %>%
  summary()

plot_data %>%
  sapply(table) %>%
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("Method") %>% 
  pivot_longer(-Method, names_to="Score", values_to="Count") %>%
  ggplot(aes(fill=Method, y=Count, x=Score)) +
    geom_bar(position="dodge", stat="identity") %>%
  return()

```

# True-Score Correlation

```{r}
cols <- df[, c("overall_1", "overall_2", "deberta_overall_1", "deberta_overall_2")] %>% 
  mutate_all(as.numeric)

# Human raters are random, so model=twoway
hum_reliability <- icc(cols[, 1:2], model="twoway", type="agreement")
# All essays were rated by the same two LLMs, so model=oneway
llm_reliability <- icc(cols[, 3:4], model="oneway", type="agreement")

mean_human = rowMeans(cols[,1:2])
mean_llm = rowMeans(cols[,3:4])
observed_cor = cor.test(mean_human, mean_llm, method="pearson", exact = FALSE)
true_corr = observed_cor$estimate / sqrt(hum_reliability$value*llm_reliability$value)

cat("Human Reliabality: ", hum_reliability$value)
cat("\nLLM Reliability: ", llm_reliability$value)
cat("\nTrue Correlation: ", true_corr)
```

## IRR

```{r}
get_perf_stats <- function(x, y) {
  x <- as.numeric(x)
  y <- as.numeric(y)
  tau <- round(KendallTauB(x, y, conf.level=.95), 3)
  cat("\nKendall Tau:", tau[1], "Lower:", tau[2], "Upper:", tau[3])
  cat("\nOdds-ratio of agreement:", round((1+tau[1])/(1-tau[1]), 3))
  cat("\nSquared Rho:", round(cor(x, y, method = "spearman")**2, 3))
}
cat("Rater 1 vs Model 1")
get_perf_stats(df$overall_1, df$deberta_overall_1)
cat("\n\nRater 2 vs Model 2")
get_perf_stats(df$overall_2, df$deberta_overall_2)
cat("\n\nRater 1 vs Rater 2")
get_perf_stats(df$overall_1, df$overall_2)
cat("\n\nModel 1 vs Model 2")
get_perf_stats(df$deberta_overall_1, df$deberta_overall_2)


png(height=1200, width=2100, file="tau_heatmap.png", type="cairo")

df %>% 
  select(overall_1, overall_2, deberta_overall_1, deberta_overall_2) %>% 
  mutate_all(as.numeric) %>% 
  setNames(c("Rater 1", "Rater 2", "Deberta 1", "Deberta 2")) %>%
  colpair_map(KendallTauB, .diagonal=1.0) %>%
  {.->>x;.} %>%
  as_matrix()  %>% 
  corrplot(addCoef.col = 'white', tl.col = 'black', tl.cex=4, number.cex=4, cl.pos="n", type="lower")

dev.off()
```

# Fit Models

```{r}
spec <- '
    overall =~
    a*overall_1 + a*overall_2
    + b*deberta_overall_1 + b*deberta_overall_2
    '

# std.lv fixes the variance of latent factors to 1
fit1 <- cfa(
  spec,
  data = df,
  std.lv=TRUE,
  ordered=TRUE,
  estimator="ULS"
  )
fit1.labels <- c("Human 1", "Human 2", "LLM 1", "LLM 2", "Proficiency")
fit1.ss <- standardizedSolution(fit1)

fit2 <- cfa(
  ' human =~ a*overall_1 + a*overall_2
    llm =~ b*deberta_overall_1 + b*deberta_overall_2
  ',
  data=df,
  std.lv=TRUE,
  ordered=TRUE,
  estimator="ULS"
  )
fit2.labels <- c("Human 1", "Human 2", "LLM 1", "LLM 2", "Proficiency\n(Human)", "Proficiency\n(LLM)")
fit2.ss <- standardizedSolution(fit2)
summary(fit1, fit.measures = TRUE)
summary(fit2, fit.measures = TRUE)
```

```{r}
fitMeasures(fit1, c("cfi","rmsea", "rmsea.ci.lower", "rmsea.ci.upper", "srmr"))
```

```{r}
parameterEstimates(fit2) %>% 
  filter(
    lhs == "human",
    rhs == "llm"
    ) %>% 
  print()
fitMeasures(fit2, c("cfi","rmsea", "rmsea.ci.lower", "rmsea.ci.upper", "srmr"))
```

```{r}
make_sem_plot <- function(fit, labels, include_estimates, filename="") {
  semPaths(
    fit,
    nodeLabels=labels,
    sizeMan=10,
    sizeLat=10,
    edge.label.cex = 1.15,
    label.cex = 1.15,
    intercepts=FALSE,
    residuals=TRUE,
    thresholds=FALSE,
    whatLabels=if (include_estimates) "est" else "no",
    filetype="png",
    filename=filename,
    mar=c(10,3,10,3)
  )
}

make_sem_plot(fit1, fit1.labels, FALSE, "one_factor_no_est")
make_sem_plot(fit2, fit2.labels, FALSE, "two_factor_no_est")
make_sem_plot(fit1, fit1.labels, TRUE, "one_factor")
make_sem_plot(fit2, fit2.labels, TRUE, "two_factor")
```

```{r}
  semPaths(
    fit2,
    nodeLabels=fit2.labels,
    sizeMan=10,
    sizeLat=10,
    edge.label.cex = 1.15,
    label.cex = 1.15,
    intercepts=FALSE,
    residuals=TRUE,
    thresholds=FALSE,
    whatLabels="est",
    mar=c(10,3,10,3)
  )
```

## Standardized Factor Loadings

```{r}
inspect(fit1,what="std")$lambda
```

```{r}
inspect(fit2,what="std")$lambda
```

## Average Variance Explained

```{r}
AVE(fit1)
```

```{r}
AVE(fit2)
```
